-- Inserindo dados de produtos
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('ground', 'Look week almost ready after above Democrat.', 108.06, 'Informática', 'https://picsum.photos/320/365', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('which', 'Pattern month available everybody happen.', 480.5, 'Informática', 'https://picsum.photos/326/245', 17);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('military', 'Any response compare capital.', 391.67, 'Acessórios', 'https://picsum.photos/393/298', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('top', 'Forget upon perform organization brother large consumer.', 379.55, 'Acessórios', 'https://picsum.photos/349/344', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('list', 'Individual both memory popular center drive.', 235.18, 'Acessórios', 'https://picsum.photos/387/254', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('leave', 'But because customer high kitchen that.', 239.32, 'Acessórios', 'https://picsum.photos/287/204', 11);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('mouth', 'Director then consider what third its owner song.', 433.07, 'Informática', 'https://picsum.photos/220/262', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('medical', 'Language stop free receive future.', 462.99, 'Informática', 'https://picsum.photos/363/347', 19);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('feel', 'Glass management want.', 86.94, 'Acessórios', 'https://picsum.photos/361/350', 4);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('for', 'Fear range six particularly.', 158.08, 'Eletronicos', 'https://picsum.photos/381/211', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('event', 'Couple loss firm six money far reveal.', 161.31, 'Eletronicos', 'https://picsum.photos/306/299', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('sea', 'Beat vote much heavy deep within.', 275.55, 'Eletronicos', 'https://picsum.photos/372/221', 6);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('all', 'Similar father couple run own cell recently.', 277.85, 'Acessórios', 'https://picsum.photos/382/335', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('newspaper', 'Military manager society buy TV alone.', 313.06, 'Acessórios', 'https://picsum.photos/221/392', 17);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('ground', 'Often activity later everything simple represent argue.', 274.21, 'Acessórios', 'https://picsum.photos/313/293', 18);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('dark', 'What body century strategy wife environment staff.', 361.3, 'Acessórios', 'https://picsum.photos/264/250', 19);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('only', 'Across worker office change writer democratic statement.', 58.37, 'Informática', 'https://picsum.photos/307/340', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('forget', 'Week mean phone little.', 452.26, 'Eletronicos', 'https://picsum.photos/239/321', 12);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('quality', 'Common if wrong whatever pass tend tell.', 414.27, 'Eletronicos', 'https://picsum.photos/371/359', 4);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('military', 'Source that high I today every suddenly else.', 353.47, 'Informática', 'https://picsum.photos/331/363', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('raise', 'While city next son.', 466.76, 'Acessórios', 'https://picsum.photos/204/299', 20);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('idea', 'This energy camera wear.', 119.49, 'Informática', 'https://picsum.photos/274/240', 12);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('election', 'Summer dream person heavy natural key.', 272.03, 'Informática', 'https://picsum.photos/323/213', 16);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('size', 'That although occur drug season.', 171.74, 'Acessórios', 'https://picsum.photos/231/323', 5);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('stand', 'Wish arrive cut sure tax.', 121.3, 'Eletronicos', 'https://picsum.photos/299/304', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('performance', 'Real system article final probably necessary ever.', 248.98, 'Eletronicos', 'https://picsum.photos/259/386', 6);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('trial', 'Green prove law call three individual hard.', 315.57, 'Informática', 'https://picsum.photos/329/218', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('option', 'Change her any nice heart major mention.', 62.61, 'Eletronicos', 'https://picsum.photos/238/265', 7);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('thousand', 'Each woman letter from find.', 133.34, 'Eletronicos', 'https://picsum.photos/294/238', 3);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('large', 'Alone outside able growth peace college.', 175.39, 'Eletronicos', 'https://picsum.photos/304/322', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('rest', 'Will white health certainly matter wonder run act.', 51.34, 'Acessórios', 'https://picsum.photos/210/370', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('option', 'Hair someone risk marriage great trouble begin top.', 137.62, 'Acessórios', 'https://picsum.photos/354/378', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('memory', 'Care nor approach top market hot.', 162.91, 'Informática', 'https://picsum.photos/234/276', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('man', 'Land choice production door majority state section.', 98.69, 'Acessórios', 'https://picsum.photos/304/391', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('strong', 'Bag himself forward who effort again.', 305.6, 'Informática', 'https://picsum.photos/224/375', 11);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('technology', 'Pm environmental woman cold story audience scientist.', 309.99, 'Eletronicos', 'https://picsum.photos/374/348', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('fast', 'Special where north will east employee reflect.', 297.84, 'Informática', 'https://picsum.photos/217/217', 1);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('such', 'Your city region customer east event.', 402.18, 'Acessórios', 'https://picsum.photos/212/335', 5);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('little', 'Area example all down beat available finally.', 324.41, 'Informática', 'https://picsum.photos/332/305', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('current', 'Hear machine site threat power end order.', 420.13, 'Eletronicos', 'https://picsum.photos/364/278', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('scene', 'Program bar win apply thought provide arm.', 442.34, 'Informática', 'https://picsum.photos/318/218', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('hope', 'Mr pattern less money food wind free.', 131.88, 'Acessórios', 'https://picsum.photos/386/320', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('yard', 'Somebody threat brother generation model.', 333.55, 'Acessórios', 'https://picsum.photos/302/272', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('do', 'Decide idea federal baby hundred.', 89.5, 'Eletronicos', 'https://picsum.photos/231/311', 17);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('effort', 'Perform recognize television year father.', 280.77, 'Informática', 'https://picsum.photos/348/312', 19);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('piece', 'Hard picture audience concern economic.', 462.1, 'Acessórios', 'https://picsum.photos/329/344', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('blood', 'Water performance imagine either truth history.', 146.85, 'Informática', 'https://picsum.photos/282/285', 17);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('she', 'Father ago baby federal break new.', 406.57, 'Acessórios', 'https://picsum.photos/229/399', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('recently', 'When employee mind cut their amount town.', 393.12, 'Informática', 'https://picsum.photos/265/307', 10);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('run', 'Season produce mouth employee.', 279.89, 'Informática', 'https://picsum.photos/284/247', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('clearly', 'Admit run half own partner.', 245.48, 'Acessórios', 'https://picsum.photos/399/236', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('significant', 'Loss single site be western peace.', 296.06, 'Eletronicos', 'https://picsum.photos/235/273', 7);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('bill', 'Garden song teach human everyone wide.', 456.66, 'Acessórios', 'https://picsum.photos/375/224', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('build', 'Option common tonight inside.', 443.57, 'Informática', 'https://picsum.photos/385/214', 10);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('question', 'Very rate plant plant production fire.', 447.11, 'Informática', 'https://picsum.photos/292/392', 5);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('age', 'Apply either central truth although improve.', 426.45, 'Eletronicos', 'https://picsum.photos/370/328', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('collection', 'College stage public several.', 277.76, 'Acessórios', 'https://picsum.photos/232/246', 19);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('understand', 'Although fine dream learn some father authority.', 222.4, 'Acessórios', 'https://picsum.photos/288/237', 3);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('glass', 'Scene find sure senior indeed if.', 482.41, 'Acessórios', 'https://picsum.photos/243/350', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('hit', 'Thus within keep skill important range.', 362.48, 'Acessórios', 'https://picsum.photos/200/385', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('field', 'Current paper because skill bank about.', 216.73, 'Acessórios', 'https://picsum.photos/256/322', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('daughter', 'Kind important structure power door cut writer.', 490.68, 'Informática', 'https://picsum.photos/313/319', 10);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('national', 'Candidate rate scientist discuss moment whether summer.', 121.1, 'Eletronicos', 'https://picsum.photos/292/295', 15);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('can', 'Government society food for company.', 347.17, 'Acessórios', 'https://picsum.photos/284/375', 4);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('toward', 'Property sure suggest black.', 387.27, 'Acessórios', 'https://picsum.photos/203/382', 18);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('state', 'Education mouth always reduce.', 387.73, 'Eletronicos', 'https://picsum.photos/205/375', 1);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('final', 'Particular war civil either draw dream ask surface.', 407.99, 'Acessórios', 'https://picsum.photos/225/371', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('moment', 'Take such activity difference nice wish suggest.', 425.88, 'Informática', 'https://picsum.photos/227/274', 14);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('maybe', 'It interest of market then chair.', 218.88, 'Acessórios', 'https://picsum.photos/270/400', 15);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('early', 'Wait reflect under talk outside in.', 239.96, 'Acessórios', 'https://picsum.photos/355/359', 7);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('nearly', 'Various easy by involve energy civil.', 112.45, 'Acessórios', 'https://picsum.photos/394/229', 17);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('feel', 'Week police get interesting project catch check.', 471.16, 'Eletronicos', 'https://picsum.photos/320/342', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('control', 'Teacher area less arrive.', 369.83, 'Acessórios', 'https://picsum.photos/261/341', 6);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('event', 'Executive thank series mouth church door.', 167.21, 'Acessórios', 'https://picsum.photos/333/202', 8);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('wall', 'Affect camera few use position two study.', 346.82, 'Eletronicos', 'https://picsum.photos/381/394', 17);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('material', 'Might memory rule start.', 149.64, 'Acessórios', 'https://picsum.photos/282/258', 19);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('close', 'New just all air expert also great worry.', 424.34, 'Acessórios', 'https://picsum.photos/337/342', 18);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('top', 'So ready attorney could also science five.', 160.27, 'Eletronicos', 'https://picsum.photos/245/374', 13);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('year', 'Happy last table whole everything concern nation specific.', 234.58, 'Informática', 'https://picsum.photos/335/226', 10);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('accept', 'Health though type ground.', 343.37, 'Eletronicos', 'https://picsum.photos/215/394', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('job', 'Simply watch edge happen large letter produce.', 339.86, 'Acessórios', 'https://picsum.photos/344/269', 11);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('woman', 'Hair second remain east until.', 66.14, 'Informática', 'https://picsum.photos/381/398', 20);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('pattern', 'Born recently soldier.', 457.17, 'Eletronicos', 'https://picsum.photos/283/296', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('why', 'Create compare how short.', 80.99, 'Informática', 'https://picsum.photos/232/290', 11);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('box', 'Few truth gas.', 289.56, 'Eletronicos', 'https://picsum.photos/262/350', 20);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('including', 'Both form possible ask.', 119.5, 'Eletronicos', 'https://picsum.photos/277/221', 15);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('little', 'Catch rule approach mother his green.', 460.38, 'Acessórios', 'https://picsum.photos/276/400', 4);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('one', 'Or upon keep similar.', 150.26, 'Acessórios', 'https://picsum.photos/347/251', 16);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('art', 'Garden production space know.', 157.56, 'Eletronicos', 'https://picsum.photos/261/221', 10);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('name', 'Become church role while lot one production.', 86.41, 'Acessórios', 'https://picsum.photos/232/278', 2);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('close', 'Audience new save rest see father inside concern.', 348.39, 'Informática', 'https://picsum.photos/301/232', 6);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('amount', 'Suddenly add professional we street world home.', 244.87, 'Informática', 'https://picsum.photos/201/308', 3);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('toward', 'Director reason town wall.', 214.01, 'Eletronicos', 'https://picsum.photos/311/393', 9);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('role', 'Daughter compare century west maintain computer.', 248.93, 'Eletronicos', 'https://picsum.photos/353/215', 1);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('despite', 'Matter interview kitchen activity now edge foot.', 364.61, 'Acessórios', 'https://picsum.photos/335/236', 4);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('country', 'Bank chance stop send check class director.', 354.15, 'Informática', 'https://picsum.photos/320/327', 3);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('miss', 'Anyone cause election bar customer song contain.', 244.52, 'Eletronicos', 'https://picsum.photos/207/246', 18);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('song', 'Sing carry look money.', 455.22, 'Acessórios', 'https://picsum.photos/386/295', 20);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('company', 'Space civil college raise.', 335.96, 'Eletronicos', 'https://picsum.photos/271/291', 10);
INSERT INTO Produto (nome, descricao, preco, categoria, imagem, estoque) VALUES ('coach', 'Foreign assume any herself idea current.', 269.94, 'Eletronicos', 'https://picsum.photos/367/273', 15);
-- Inserindo dados de usuários
INSERT INTO Usuario (nome, email, senha) VALUES ('Usuário 1', 'usuario1@exemplo.com', 'senha123');
INSERT INTO Usuario (nome, email, senha) VALUES ('Usuário 2', 'usuario2@exemplo.com', 'senha456');

